BlogApp/urls.py
from django.conf import settings
from django.urls import path
from . import views
from .views import *
app_name="Blogapp"
urlpatterns = [
    path('',views.index,name="index"),
    path('blog/',views.blog,name="blog"),
    path('post/<id>/',views.post,name="post"),
    path('post/update/<id>/',views.post_update,name="update"),
    path('post/delete/<id>/',views.post_delete,name="delete"),
    path('create/',views.post_create,name="create"),
    path('search/',views.search,name="search"),  
    path('vote/up/<id>/',views.post_vote_up,name="post-vote-up"),  
    path('vote/down/<id>/',views.post_vote_down,name="post-vote-down"),
    path("contact/",views.Contact,name="contact"),
    path("profile/<id>",views.profile,name="profile"),
    # Admin Urls
    path('dashboard/posts/',views.Admin,name="admin"),
    path('dashboard/posts/update/<id>/',views.Admin_Post_Update,name="admin-update"),
    path('dashboard/posts/delete/<id>/',views. Admin_Post_Delete,name="admin-delete"),    
    path('dashboard/user/delete/<id>/',views. Admin_User_Delete,name="admin-user-delete"),    
]

blog/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include




urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("BlogApp.urls",namespace="home")),
    path("marketing/",include("marketing.urls",namespace="marketing")),
    #this is the TextEditor
    path('ckeditor/', include('ckeditor_uploader.urls')),
    #Django allauth
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/admin.html
{% extends "base.html" %}

{% block content %}
<div class="container m-5">
<div class="row">
    <div class="col">
<h1>Admin</h1>
<h3>Posts</h3>



<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">posts</th>
         <th scope="col">post view</th>
        <th scope="col">post action</th>
        <th scope="col">user</th>
        <th scope="col">user action</th>
      </tr>
    </thead>
    <tbody>
        {% for post in posts %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{post.title}}</td>
        <td><a href="{{post.get_absolute_url}}">view post</a></td>
        <td>
          <a href="{% url 'home:admin-update' id=post.id %}">update</a>
          <a href="{% url 'home:admin-delete' id=post.id %}">delete</a>
        </td>
        <td>{{post.user.first_name}}</td>
        <td><a href="{% url 'home:admin-user-delete' id=post.user.id %}">delete user</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
    
    </div>
</div>

</div>

{% endblock %}

templates/admin_post_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-5 mb-5">
<div class="row">
    <div class="col">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
           {{form|crispy}}
           <button class="btn btn-primary" type="submit">Submit</button>
        </form>
      
       
    </div>
</div>


</div>


{% endblock %}

templates/blog.html
  {% extends "base.html" %}
{% load static %}

  
  {% block content %}
  <div class="container">
    <div class="row">
      <!-- Latest Posts -->
      <main class="posts-listing col-lg-8"> 
        <div class="container">
          <div class="row">
            <!-- post -->
            {% for post in pagination %}
            <div class="post col-xl-6">
              <div id="blog-photo" class="post-thumbnail"><a href="{{post.get_absolute_url}}"><img src="{{post.image.url}}"  alt="..." class="img-fluid"></a></div>
              <div id="blog-img" class="post-details">
                <div class="post-meta d-flex justify-content-between">
                  <div class="date meta-last">{{post.timestamp|date:"d M"}}| {{post.timestamp|date:"Y"}}</div>
                  <div class="category">
                    {% for i in post.category.all|slice:"0:2" %}
                    <a href="{{post.get_absolute_url}}">{{i.title}}</a>
                    {% endfor %}
                  </div>
                </div>
                <a href="{{post.get_absolute_url}}">
                  <h3 class="h4">{{post.title}}</h3></a>
                <p class="text-muted">{{post.overviews|truncatewords_html:10|safe}}</p>
                <footer class="post-footer d-flex align-items-center"><a href="{{post.get_absolute_url}}" class="author d-flex align-items-center flex-wrap">
    
                  <div id="blog-avatar" class="avatar"><img src="{{post.user.author.image.url}}" alt="..." class="img-fluid"></div>
              
                  <div class="title"><span>{{post.user.first_name}} {{post.user.last_name}}</span></div></a>
                  <div class="date"><i class="icon-clock"></i>{{post.timestamp|date:"D m Y"}}</div>
                  <div class="comments meta-last"><i class="icon-comment"></i>{{post.comments.count}}</div>
                </footer>
              </div>
            </div>
          {% endfor %}
        

          </div>

          <!-- Pagination -->

          <!-- <nav aria-label="Page navigation example">
            <ul class="pagination pagination-template d-flex justify-content-center">
              <li class="page-item"><a href="#" class="page-link"> <i class="fa fa-angle-left"></i></a></li>
              <li class="page-item"><a href="#" class="page-link active">1</a></li>
              <li class="page-item"><a href="#" class="page-link">2</a></li>
              <li class="page-item"><a href="#" class="page-link">3</a></li>
              <li class="page-item"><a href="#" class="page-link"> <i class="fa fa-angle-right"></i></a></li>
            </ul>
          </nav> -->
      
        </div>
      </main>
      <aside class="col-lg-4">
        <!-- Widget [Search Bar Widget]-->
        <div class="widget search">
          <header>
            <h3 class="h6">Search the blog</h3>
          </header>
          <form  action="{% url 'home:search' %}"class="search-form">
            <div class="form-group">
              <input type="search" name="q" placeholder="What are you looking for?">
              <button type="submit" class="submit"><i class="icon-search"></i></button>
            </div>
          </form>
        </div>
        <!-- Widget [Latest Posts Widget]        -->
        <div class="widget latest-posts">
          <header>
            <h3 class="h6">Latest Posts</h3>
          </header>
          {% for post in latest %}
          <div class="blog-posts"><a href="{{post.get_absolute_url}}">
              <div class="item d-flex align-items-center">
                <div  class="image"><img src="{{post.image.url}}" alt="..." class="img-fluid"></div>
                <div class="title"><strong>{{post.title}}</strong>
                  <div class="d-flex align-items-center">
                    <div class="views"><i class="icon-eye"></i> {{post.view_count}}</div>
                    <div class="comments"><i class="icon-comment"></i>{{post.comments.count}}</div>
                  </div>
                </div>
              </div>
            </a>
            </div>
            {% endfor %}
        </div>
        <!-- Widget [Categories Widget]-->
        <div class="widget categories">
          <header>
            <h3 class="h6">Categories</h3>
          </header>
          {% for cat in category_count %}
          <div class="item d-flex justify-content-between"><a href="#">{{cat.category__title}}</a><span>{{cat.category__count}}</span></div>
            {% endfor %}
        </div>
        <!-- Widget [Tags Cloud Widget]-->
        <div class="widget tags">       
          <header>
            <h3 class="h6">Tags</h3>
          </header>
          <ul class="list-inline">
            {% for tag in tags %}
            <li class="list-inline-item"><a href="#" class="tag">#{{tag}}</a></li>
            {% endfor %}
          </ul>
        </div>
      </aside>
    </div>
  </div>
{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}



{% block content %}
<div class="container m-5">
    <h1 id="contact">Contact Us</h1>
    <div class="row">
        <div class="col col-lg-12">
<form method="POST">
    {% csrf_token %}

    {{form|crispy}}
    <input type="submit" value="Submit"  class='btn btn-primary'>



</form>
            

        </div>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}



{% block content %}


    <!-- Hero Section-->
    <section style="background: url({% static 'img/hero.jpg' %}); background-size: cover; background-position: center center" class="hero">
      <div class="container">
        <div class="row">
          <div class="col-lg-7">
            <h1>Welcome toy our Blog</h1><a href="{% url 'home:blog' %}" class="hero-link">Discover More</a>
          </div>
        </div><a href=".intro" class="continue link-scroll"><i class="fa fa-long-arrow-down"></i> Scroll Down</a>
      </div>
    </section>
    <!-- Intro Section-->
    <section class="intro">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <h2 class="h3">Some great intro here</h2>
            <p class="text-big">Place a nice <strong>introduction</strong> here <strong>to catch reader's attention</strong>. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderi.</p>
          </div>
        </div>
      </div>
    </section>

    <section class="featured-posts no-padding">
      <div  class="container">
        <!-- Post-->
        {% for post in posts %}
        <div class="row d-flex align-items-stretch p-2">
          {% if not forloop.first and not forloop.last %}
          <div class="image col-lg-5"><img src="{{post.image.url}}" alt="{{post.title}}"></div>
          {% endif %}
          <div id="index-text" class="text col-lg-7">
            <div class="text-inner d-flex align-items-center">
              <div id="blog-img" class="content">
                <header class="post-header">
                  <div class="category">
                    {% for i in post.category.all %}
                    <a href="{{post.get_absolute_url}}">{{i.title}}</a>
                   {% endfor %}
                  </div>
                  <a href="{{post.get_absolute_url}}">
                    <h2 class="h4">{{post.title}}</h2></a>
                </header>
                <p>{{post.overviews|safe|truncatewords_html:10}}</p>
                <footer class="post-footer d-flex align-items-center"><a href="{{post.get_absolute_url}}" class="author d-flex align-items-center flex-wrap">
                    <div id="blog-avatar" class="avatar"><img src="{{post.user.author.image.url}}" alt="{{post.user.first_name}}" class="img-fluid"></div>
                    <div class="title"><span>{{post.user.get_full_name.title}}</span></div></a>
                  <div class="date"><i class="icon-clock"></i>{{post.timestamp|timesince}}</div>
                  <div class="comments"><i class="icon-comment"></i>{{post.comments.count}}</div>
                </footer>
              </div>
            </div>
          </div>
          
          {% if forloop.first or forloop.last %}
          <div class="image col-lg-5"><img src="{{post.image.url}}" alt="..."></div>
          {% endif %}
        </div>
          {% endfor %}
        <!-- Post        -->

      </div>
    </section>

    <!-- Divider Section-->
    <section style="background: url({% static 'img/divider-bg.jpg' %}); background-size: cover; background-position: center bottom" class="divider">
      <div class="container">
        <div class="row">
          <div class="col-md-7">
            <h2>we got more and more...</h2><a href="{% url 'home:blog' %}" class="hero-link">View More</a>
          </div>
        </div>
      </div>
    </section>
    <!-- Latest Posts -->
    <section class="latest-posts"> 
      <div class="container">
        <header> 
          <h2>Latest from the blog</h2>
          <p class="text-big">our latest posts</p>
        </header>
        <div class="row">
          {% for post in latest %}
          <div class="post col-md-4">
            <div class="post-thumbnail"><a href="{{post.get_absolute_url}}"><img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid"></a></div>
            <div id="blog-img" class="post-details">
              <div class="post-meta d-flex justify-content-between">
                <div class="date">{{post.timestamp|date:"M d"}} | {{post.timestamp|date:"Y"}}</div>
                <div class="category">
                  {% for i in post.category.all|slice:"0:2" %}
                  <a href="{{post.get_absolute_url}}">{{i.title}}</a>
                  {% endfor %}
                </div>
              </div><a href="{{psot.get_absolute_url}}">
                <h3 class="h4">{{post.title}}</h3></a>
              <p class="text-muted">{{post.overviews|truncatewords_html:10|safe}}</p>
            </div>
          </div>
      {% endfor %}
        </div>
      </div>
    </section>
    <!-- Newsletter Section-->
    <section class="newsletter no-padding-top">    
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <h2>Subscribe to Newsletter</h2>
            <p class="text-big">Subscribe to get latest news from our Blog </p>
          </div>
          <div class="col-md-8">
            <div class="form-holder">
              <form action="{% url 'home:index' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                  <input type="email" name="email" id="email" placeholder="Type your email address">
                  <button type="submit" class="submit">Subscribe</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- Gallery Section-->
    <section class="gallery">    
      <div class="row">
        <div class="mix col-lg-3 col-md-3 col-sm-6">
          <div class="item"><a href="{% static 'img/gallery-1.jpg' %}" data-fancybox="gallery" class="image"><img src="{% static 'img/gallery-1.jpg' %}" alt="..." class="img-fluid">
              <div class="overlay d-flex align-items-center justify-content-center"><i class="icon-search"></i></div></a></div>
        </div>
        <div class="mix col-lg-3 col-md-3 col-sm-6">
          <div class="item"><a href="{% static 'img/gallery-2.jpg' %}" data-fancybox="gallery" class="image"><img src="{% static 'img/gallery-2.jpg' %}" alt="..." class="img-fluid">
              <div class="overlay d-flex align-items-center justify-content-center"><i class="icon-search"></i></div></a></div>
        </div>
        <div class="mix col-lg-3 col-md-3 col-sm-6">
          <div class="item"><a href="{% static 'img/gallery-3.jpg' %}" data-fancybox="gallery" class="image"><img src="{% static 'img/gallery-3.jpg' %}" alt="..." class="img-fluid">
              <div class="overlay d-flex align-items-center justify-content-center"><i class="icon-search"></i></div></a></div>
        </div>
        <div class="mix col-lg-3 col-md-3 col-sm-6">
          <div class="item"><a href="{% static 'img/gallery-4.jpg' %}" data-fancybox="gallery" class="image"><img src="{% static 'img/gallery-4.jpg' %}" alt="..." class="img-fluid">
              <div class="overlay d-flex align-items-center justify-content-center"><i class="icon-search"></i></div></a></div>
        </div>
      </div>
    </section>
   {% endblock %}

templates/post_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container m-5">
<div class="row">
    <div class="col">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
           {{form|crispy}}
           <button class="btn btn-primary" type="submit">Submit</button>
        </form>
      
       
    </div>
</div>


</div>


{% endblock %}

templates/post_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-5 mb-5">
<div class="row">
    <div class="col">
        <form method="POST" id="update-form" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
           {{form|crispy}}
           <button class="btn btn-primary" type="submit">Submit</button>
        </form>
      
       
    </div>
</div>


</div>


{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<body id="prfoile-body">

<div class="container m-5">
    <div class="row gutters">
        <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
            <div class="card h-100">
                <div class="card-body">
                    <div class="account-settings">
                        <div class="user-profile">
                            <div class="user-avatar">
                                <img src="{{profile.image.url}}" alt="{{request.user}}">
                            </div>
                            <h5 class="user-name">{{profile.user.get_gull_name|title}}</h5>
                            <h6 class="user-email">{{request.user.email}}</h6>
                        </div>
                        <div class="about">
                            <h5 class="mb-2 text-primary">About</h5>
                            <p>I'm {{request.user.first_name|title}}.iam a Web Developer I enjoy creating user-centric, delightful and human experiences.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
  
        <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
            <div class="card h-100">
                <div class="card-body">
                    <div class="row gutters">
                        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                            <h6 class="mb-3 text-primary">Personal Details</h6>
                        </div>
        <form method="POST" enctype="multipart/form-data">
{% csrf_token %}
                       {{form|crispy}}
                       <input type="submit" class="btn btn-primary" value="Submit">
                    </form>
                    </div>
                
                </div>
            </div>
        </div>
      
    </div>
    </div>
</body>
    {% endblock %}

templates/search.html
  {% extends "base.html" %}
  {% load static %}
  
    
    {% block content %}
    <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="posts-listing col-lg-8"> 
          <div class="container">
            <div class="row">
              <!-- post -->
              {% if qs %}
              <div class="col col-lg-12">
                <h2>search results for "{{request.GET.q}}"</h2>
              </div>
              {% for post in qs %}
              <div class="post col-xl-6">
                <div class="post-thumbnail"><a href="{{post.get_absolute_url}}"><img src="{{post.image.url}}"  alt="..." class="img-fluid"></a></div>
                <div id="blog-img" class="post-details">
                  <div class="post-meta d-flex justify-content-between">
                    <div class="date meta-last">{{post.timestamp|date:"d M"}}| {{post.timestamp|date:"Y"}}</div>
                    <div class="category">
                      {% for i in post.category.all|slice:"0:2" %}
                      <a href="{{post.get_absolute_url}}">{{i.title}}</a>
                      {% endfor %}
                    </div>
                  </div>
                  <a href="{{post.get_absolute_url}}">
                    <h3 class="h4">{{post.title}}</h3></a>
                  <p class="text-muted">{{post.overviews|truncatewords_html:10|safe}}</p>
                  <footer class="post-footer d-flex align-items-center"><a href="{{post.get_absolute_url}}" class="author d-flex align-items-center flex-wrap">
      
                    <div id="blog-avatar" class="avatar"><img src="{{post.user.author.image.url}}" alt="..." class="img-fluid"></div>
                
                    <div class="title"><span>{{post.user.first_name}} {{post.user.last_name}}</span></div></a>
                    <div class="date"><i class="icon-clock"></i>{{post.timestamp|date:"D m Y"}}</div>
                    <div class="comments meta-last"><i class="icon-comment"></i>{{post.comments.count}}</div>
                  </footer>
                </div>
              </div>
            {% endfor %}
          {% else %}
          <h2>sorry we dont have what you are looking for</h2>
  {% endif %}
            </div>
  
            <!-- Pagination -->
  
            <!-- <nav aria-label="Page navigation example">
              <ul class="pagination pagination-template d-flex justify-content-center">
                <li class="page-item"><a href="#" class="page-link"> <i class="fa fa-angle-left"></i></a></li>
                <li class="page-item"><a href="#" class="page-link active">1</a></li>
                <li class="page-item"><a href="#" class="page-link">2</a></li>
                <li class="page-item"><a href="#" class="page-link">3</a></li>
                <li class="page-item"><a href="#" class="page-link"> <i class="fa fa-angle-right"></i></a></li>
              </ul>
            </nav> -->
        
          </div>
        </main>
        <aside class="col-lg-4">
          <!-- Widget [Search Bar Widget]-->
          <div class="widget search">
            <header>
              <h3 class="h6">Search the blog</h3>
            </header>
            <form  action="{% url 'home:search' %}"class="search-form">
              <div class="form-group">
                <input type="search" name="q" placeholder="What are you looking for?">
                <button type="submit" class="submit"><i class="icon-search"></i></button>
              </div>
            </form>
          </div>
          <!-- Widget [Latest Posts Widget]        -->
          <div class="widget latest-posts">
            <header>
              <h3 class="h6">Latest Posts</h3>
            </header>
            {% for post in latest %}
            <div class="blog-posts"><a href="{{post.get_absolute_url}}">
                <div class="item d-flex align-items-center">
                  <div class="image"><img src="{{post.image.url}}" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>{{post.title}}</strong>
                    <div class="d-flex align-items-center">
                      <div class="views"><i class="icon-eye"></i> {{post.views_count}}</div>
                      <div class="comments"><i class="icon-comment"></i>{{post.comments.count}}</div>
                    </div>
                  </div>
                </div>
              </a>
              </div>
              {% endfor %}
          </div>
          <!-- Widget [Categories Widget]-->
          <div class="widget categories">
            <header>
              <h3 class="h6">Categories</h3>
            </header>
            {% for cat in category_count %}
            <div class="item d-flex justify-content-between"><a href="#">{{cat.category__title}}</a><span>{{cat.category__count}}</span></div>
              {% endfor %}
          </div>
          <!-- Widget [Tags Cloud Widget]-->
       
        </aside>
      </div>
    </div>
  {% endblock %}